### ISSUE TITLE
CDN Internal Server Error

### ISSUE THREAD

**Issue by nikramakrishnan** [anuditnagar/darklms#2]
The `gitcdn.xyz` [link](https://gitcdn.xyz/repo/anuditnagar/darklms/master/darklms.min.css) for the CSS gives an internal server error. This has been the case for the last few days. Can you check? Thanks!

**Comment by nikramakrishnan** [comment]
Hm, OK never mind. The thing fixed itself just minutes after I added the issue. Weird 😕

**Comment by nikramakrishnan** [comment]
OK this CDN is acting up again:

![image](https://user-images.githubusercontent.com/10017618/57305886-62ea3b80-70ff-11e9-957b-2eaad9fcf567.png)

Do we have any other options?

**Comment by anudit** [comment]
Links Updated : https://github.com/anuditnagar/darklms/commit/90e378fb953a40b4fb7ca3998586e7434dc6b40e

Thanks!

**Comment by nikramakrishnan** [comment]
Great, this seems to be faster. Greasyfork script updated!
